<?xml version="1.0" encoding="utf-8"?><Database Name="LTWNC" Class="QLTVDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-VA3QE2VM\SQLEXPRESS;Initial Catalog=LTWNC;Integrated Security=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="LTWNCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QL_TheLoai" Member="QL_TheLoais">
    <Type Name="QL_TheLoai">
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_TheLoai_QL_TaiLieu" Member="QL_TaiLieus" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="QL_TaiLieu" />
    </Type>
  </Table>
  <Table Name="dbo.QL_ViTri" Member="QL_ViTris">
    <Type Name="QL_ViTri">
      <Column Name="MaViTri" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenViTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_ViTri_QL_TaiLieu" Member="QL_TaiLieus" ThisKey="MaViTri" OtherKey="ViTri" Type="QL_TaiLieu" />
    </Type>
  </Table>
  <Table Name="dbo.QL_TaiLieu" Member="QL_TaiLieus">
    <Type Name="QL_TaiLieu">
      <Column Name="MaTaiLieu" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTheLoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ViTri" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AnhQR" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TenTaiLieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LinkTaiLieu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="QL_TaiLieu_QL_MuonTra" Member="QL_MuonTras" ThisKey="MaTaiLieu" OtherKey="MaTaiLieu" Type="QL_MuonTra" />
      <Association Name="QL_TheLoai_QL_TaiLieu" Member="QL_TheLoai" ThisKey="MaTheLoai" OtherKey="MaTheLoai" Type="QL_TheLoai" IsForeignKey="true" />
      <Association Name="QL_ViTri_QL_TaiLieu" Member="QL_ViTri" ThisKey="ViTri" OtherKey="MaViTri" Type="QL_ViTri" IsForeignKey="true" />
      <Association Name="QL_TacGia_QL_TaiLieu" Member="QL_TacGia" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="QL_TacGia" IsForeignKey="true" />
      <Association Name="QL_NhaXuatBan_QL_TaiLieu" Member="QL_NhaXuatBan" ThisKey="MaNXB" OtherKey="MaNXB" Type="QL_NhaXuatBan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_TacGia" Member="QL_TacGias">
    <Type Name="QL_TacGia">
      <Column Name="MaTacGia" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTacGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_TacGia_QL_TaiLieu" Member="QL_TaiLieus" ThisKey="MaTacGia" OtherKey="MaTacGia" Type="QL_TaiLieu" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NhomCuaNguoiDung" Member="QL_NhomCuaNguoiDungs">
    <Type Name="QL_NhomCuaNguoiDung">
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNhom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Quyen" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="QL_NhomCuaNguoiDung_QL_NguoiDung" Member="QL_NguoiDungs" ThisKey="MaNhom" OtherKey="MaNhom" Type="QL_NguoiDung" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NguoiDung" Member="QL_NguoiDungs">
    <Type Name="QL_NguoiDung">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNhom" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="QL_NguoiDung_QL_MuonTra" Member="QL_MuonTras" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="QL_MuonTra" />
      <Association Name="QL_NhomCuaNguoiDung_QL_NguoiDung" Member="QL_NhomCuaNguoiDung" ThisKey="MaNhom" OtherKey="MaNhom" Type="QL_NhomCuaNguoiDung" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_NhaXuatBan" Member="QL_NhaXuatBans">
    <Type Name="QL_NhaXuatBan">
      <Column Name="MaNXB" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NhaXuatBan_QL_TaiLieu" Member="QL_TaiLieus" ThisKey="MaNXB" OtherKey="MaNXB" Type="QL_TaiLieu" />
    </Type>
  </Table>
  <Table Name="dbo.QL_MuonTra" Member="QL_MuonTras">
    <Type Name="QL_MuonTra">
      <Column Name="MaPhieuMuon" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaTaiLieu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuongMuon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayMuon" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaDocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_NguoiDung_QL_MuonTra" Member="QL_NguoiDung" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="QL_NguoiDung" IsForeignKey="true" />
      <Association Name="QL_TaiLieu_QL_MuonTra" Member="QL_TaiLieu" ThisKey="MaTaiLieu" OtherKey="MaTaiLieu" Type="QL_TaiLieu" IsForeignKey="true" />
      <Association Name="QL_DocGia_QL_MuonTra" Member="QL_DocGia" ThisKey="MaDocGia" OtherKey="MaDocGia" Type="QL_DocGia" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_LoaiDocGia" Member="QL_LoaiDocGias">
    <Type Name="QL_LoaiDocGia">
      <Column Name="MaLoaiDocGia" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiDocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_DocGia" Member="QL_DocGias">
    <Type Name="QL_DocGia">
      <Column Name="MaDocGia" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Anh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Emai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiDocGia" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="QL_DocGia_QL_MuonTra" Member="QL_MuonTras" ThisKey="MaDocGia" OtherKey="MaDocGia" Type="QL_MuonTra" />
    </Type>
  </Table>
</Database>