#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LTWNC")]
	public partial class QLTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQL_TheLoai(QL_TheLoai instance);
    partial void UpdateQL_TheLoai(QL_TheLoai instance);
    partial void DeleteQL_TheLoai(QL_TheLoai instance);
    partial void InsertQL_ViTri(QL_ViTri instance);
    partial void UpdateQL_ViTri(QL_ViTri instance);
    partial void DeleteQL_ViTri(QL_ViTri instance);
    partial void InsertQL_TaiLieu(QL_TaiLieu instance);
    partial void UpdateQL_TaiLieu(QL_TaiLieu instance);
    partial void DeleteQL_TaiLieu(QL_TaiLieu instance);
    partial void InsertQL_TacGia(QL_TacGia instance);
    partial void UpdateQL_TacGia(QL_TacGia instance);
    partial void DeleteQL_TacGia(QL_TacGia instance);
    partial void InsertQL_NhomCuaNguoiDung(QL_NhomCuaNguoiDung instance);
    partial void UpdateQL_NhomCuaNguoiDung(QL_NhomCuaNguoiDung instance);
    partial void DeleteQL_NhomCuaNguoiDung(QL_NhomCuaNguoiDung instance);
    partial void InsertQL_NguoiDung(QL_NguoiDung instance);
    partial void UpdateQL_NguoiDung(QL_NguoiDung instance);
    partial void DeleteQL_NguoiDung(QL_NguoiDung instance);
    partial void InsertQL_NhaXuatBan(QL_NhaXuatBan instance);
    partial void UpdateQL_NhaXuatBan(QL_NhaXuatBan instance);
    partial void DeleteQL_NhaXuatBan(QL_NhaXuatBan instance);
    partial void InsertQL_MuonTra(QL_MuonTra instance);
    partial void UpdateQL_MuonTra(QL_MuonTra instance);
    partial void DeleteQL_MuonTra(QL_MuonTra instance);
    partial void InsertQL_LoaiDocGia(QL_LoaiDocGia instance);
    partial void UpdateQL_LoaiDocGia(QL_LoaiDocGia instance);
    partial void DeleteQL_LoaiDocGia(QL_LoaiDocGia instance);
    partial void InsertQL_DocGia(QL_DocGia instance);
    partial void UpdateQL_DocGia(QL_DocGia instance);
    partial void DeleteQL_DocGia(QL_DocGia instance);
    #endregion
		
		public QLTVDataContext() : 
				base(global::DAL.Properties.Settings.Default.LTWNCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QL_TheLoai> QL_TheLoais
		{
			get
			{
				return this.GetTable<QL_TheLoai>();
			}
		}
		
		public System.Data.Linq.Table<QL_ViTri> QL_ViTris
		{
			get
			{
				return this.GetTable<QL_ViTri>();
			}
		}
		
		public System.Data.Linq.Table<QL_TaiLieu> QL_TaiLieus
		{
			get
			{
				return this.GetTable<QL_TaiLieu>();
			}
		}
		
		public System.Data.Linq.Table<QL_TacGia> QL_TacGias
		{
			get
			{
				return this.GetTable<QL_TacGia>();
			}
		}
		
		public System.Data.Linq.Table<QL_NhomCuaNguoiDung> QL_NhomCuaNguoiDungs
		{
			get
			{
				return this.GetTable<QL_NhomCuaNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_NguoiDung> QL_NguoiDungs
		{
			get
			{
				return this.GetTable<QL_NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_NhaXuatBan> QL_NhaXuatBans
		{
			get
			{
				return this.GetTable<QL_NhaXuatBan>();
			}
		}
		
		public System.Data.Linq.Table<QL_MuonTra> QL_MuonTras
		{
			get
			{
				return this.GetTable<QL_MuonTra>();
			}
		}
		
		public System.Data.Linq.Table<QL_LoaiDocGia> QL_LoaiDocGias
		{
			get
			{
				return this.GetTable<QL_LoaiDocGia>();
			}
		}
		
		public System.Data.Linq.Table<QL_DocGia> QL_DocGias
		{
			get
			{
				return this.GetTable<QL_DocGia>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_TheLoai")]
	public partial class QL_TheLoai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTheLoai;
		
		private string _TenTheLoai;
		
		private EntitySet<QL_TaiLieu> _QL_TaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTheLoaiChanging(string value);
    partial void OnMaTheLoaiChanged();
    partial void OnTenTheLoaiChanging(string value);
    partial void OnTenTheLoaiChanged();
    #endregion
		
		public QL_TheLoai()
		{
			this._QL_TaiLieus = new EntitySet<QL_TaiLieu>(new Action<QL_TaiLieu>(this.attach_QL_TaiLieus), new Action<QL_TaiLieu>(this.detach_QL_TaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTheLoai
		{
			get
			{
				return this._MaTheLoai;
			}
			set
			{
				if ((this._MaTheLoai != value))
				{
					this.OnMaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoai = value;
					this.SendPropertyChanged("MaTheLoai");
					this.OnMaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTheLoai", DbType="NVarChar(50)")]
		public string TenTheLoai
		{
			get
			{
				return this._TenTheLoai;
			}
			set
			{
				if ((this._TenTheLoai != value))
				{
					this.OnTenTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenTheLoai = value;
					this.SendPropertyChanged("TenTheLoai");
					this.OnTenTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TheLoai_QL_TaiLieu", Storage="_QL_TaiLieus", ThisKey="MaTheLoai", OtherKey="MaTheLoai")]
		public EntitySet<QL_TaiLieu> QL_TaiLieus
		{
			get
			{
				return this._QL_TaiLieus;
			}
			set
			{
				this._QL_TaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TheLoai = this;
		}
		
		private void detach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TheLoai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ViTri")]
	public partial class QL_ViTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaViTri;
		
		private string _TenViTri;
		
		private EntitySet<QL_TaiLieu> _QL_TaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaViTriChanging(string value);
    partial void OnMaViTriChanged();
    partial void OnTenViTriChanging(string value);
    partial void OnTenViTriChanged();
    #endregion
		
		public QL_ViTri()
		{
			this._QL_TaiLieus = new EntitySet<QL_TaiLieu>(new Action<QL_TaiLieu>(this.attach_QL_TaiLieus), new Action<QL_TaiLieu>(this.detach_QL_TaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this.OnMaViTriChanging(value);
					this.SendPropertyChanging();
					this._MaViTri = value;
					this.SendPropertyChanged("MaViTri");
					this.OnMaViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenViTri", DbType="NVarChar(50)")]
		public string TenViTri
		{
			get
			{
				return this._TenViTri;
			}
			set
			{
				if ((this._TenViTri != value))
				{
					this.OnTenViTriChanging(value);
					this.SendPropertyChanging();
					this._TenViTri = value;
					this.SendPropertyChanged("TenViTri");
					this.OnTenViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ViTri_QL_TaiLieu", Storage="_QL_TaiLieus", ThisKey="MaViTri", OtherKey="ViTri")]
		public EntitySet<QL_TaiLieu> QL_TaiLieus
		{
			get
			{
				return this._QL_TaiLieus;
			}
			set
			{
				this._QL_TaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_ViTri = this;
		}
		
		private void detach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_ViTri = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_TaiLieu")]
	public partial class QL_TaiLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiLieu;
		
		private string _MaTheLoai;
		
		private string _MaNXB;
		
		private string _MaTacGia;
		
		private string _ViTri;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Data.Linq.Binary _AnhQR;
		
		private string _TenTaiLieu;
		
		private string _LinkTaiLieu;
		
		private EntitySet<QL_MuonTra> _QL_MuonTras;
		
		private EntityRef<QL_TheLoai> _QL_TheLoai;
		
		private EntityRef<QL_ViTri> _QL_ViTri;
		
		private EntityRef<QL_TacGia> _QL_TacGia;
		
		private EntityRef<QL_NhaXuatBan> _QL_NhaXuatBan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiLieuChanging(string value);
    partial void OnMaTaiLieuChanged();
    partial void OnMaTheLoaiChanging(string value);
    partial void OnMaTheLoaiChanged();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    partial void OnMaTacGiaChanging(string value);
    partial void OnMaTacGiaChanged();
    partial void OnViTriChanging(string value);
    partial void OnViTriChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnAnhQRChanging(System.Data.Linq.Binary value);
    partial void OnAnhQRChanged();
    partial void OnTenTaiLieuChanging(string value);
    partial void OnTenTaiLieuChanged();
    partial void OnLinkTaiLieuChanging(string value);
    partial void OnLinkTaiLieuChanged();
    #endregion
		
		public QL_TaiLieu()
		{
			this._QL_MuonTras = new EntitySet<QL_MuonTra>(new Action<QL_MuonTra>(this.attach_QL_MuonTras), new Action<QL_MuonTra>(this.detach_QL_MuonTras));
			this._QL_TheLoai = default(EntityRef<QL_TheLoai>);
			this._QL_ViTri = default(EntityRef<QL_ViTri>);
			this._QL_TacGia = default(EntityRef<QL_TacGia>);
			this._QL_NhaXuatBan = default(EntityRef<QL_NhaXuatBan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiLieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiLieu
		{
			get
			{
				return this._MaTaiLieu;
			}
			set
			{
				if ((this._MaTaiLieu != value))
				{
					this.OnMaTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._MaTaiLieu = value;
					this.SendPropertyChanged("MaTaiLieu");
					this.OnMaTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTheLoai", DbType="NVarChar(50)")]
		public string MaTheLoai
		{
			get
			{
				return this._MaTheLoai;
			}
			set
			{
				if ((this._MaTheLoai != value))
				{
					if (this._QL_TheLoai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTheLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaTheLoai = value;
					this.SendPropertyChanged("MaTheLoai");
					this.OnMaTheLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="NVarChar(50)")]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					if (this._QL_NhaXuatBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTacGia", DbType="NVarChar(50)")]
		public string MaTacGia
		{
			get
			{
				return this._MaTacGia;
			}
			set
			{
				if ((this._MaTacGia != value))
				{
					if (this._QL_TacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaTacGia = value;
					this.SendPropertyChanged("MaTacGia");
					this.OnMaTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="NVarChar(50)")]
		public string ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					if (this._QL_ViTri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhQR", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AnhQR
		{
			get
			{
				return this._AnhQR;
			}
			set
			{
				if ((this._AnhQR != value))
				{
					this.OnAnhQRChanging(value);
					this.SendPropertyChanging();
					this._AnhQR = value;
					this.SendPropertyChanged("AnhQR");
					this.OnAnhQRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiLieu", DbType="NVarChar(50)")]
		public string TenTaiLieu
		{
			get
			{
				return this._TenTaiLieu;
			}
			set
			{
				if ((this._TenTaiLieu != value))
				{
					this.OnTenTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._TenTaiLieu = value;
					this.SendPropertyChanged("TenTaiLieu");
					this.OnTenTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkTaiLieu", DbType="NVarChar(MAX)")]
		public string LinkTaiLieu
		{
			get
			{
				return this._LinkTaiLieu;
			}
			set
			{
				if ((this._LinkTaiLieu != value))
				{
					this.OnLinkTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._LinkTaiLieu = value;
					this.SendPropertyChanged("LinkTaiLieu");
					this.OnLinkTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TaiLieu_QL_MuonTra", Storage="_QL_MuonTras", ThisKey="MaTaiLieu", OtherKey="MaTaiLieu")]
		public EntitySet<QL_MuonTra> QL_MuonTras
		{
			get
			{
				return this._QL_MuonTras;
			}
			set
			{
				this._QL_MuonTras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TheLoai_QL_TaiLieu", Storage="_QL_TheLoai", ThisKey="MaTheLoai", OtherKey="MaTheLoai", IsForeignKey=true)]
		public QL_TheLoai QL_TheLoai
		{
			get
			{
				return this._QL_TheLoai.Entity;
			}
			set
			{
				QL_TheLoai previousValue = this._QL_TheLoai.Entity;
				if (((previousValue != value) 
							|| (this._QL_TheLoai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_TheLoai.Entity = null;
						previousValue.QL_TaiLieus.Remove(this);
					}
					this._QL_TheLoai.Entity = value;
					if ((value != null))
					{
						value.QL_TaiLieus.Add(this);
						this._MaTheLoai = value.MaTheLoai;
					}
					else
					{
						this._MaTheLoai = default(string);
					}
					this.SendPropertyChanged("QL_TheLoai");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ViTri_QL_TaiLieu", Storage="_QL_ViTri", ThisKey="ViTri", OtherKey="MaViTri", IsForeignKey=true)]
		public QL_ViTri QL_ViTri
		{
			get
			{
				return this._QL_ViTri.Entity;
			}
			set
			{
				QL_ViTri previousValue = this._QL_ViTri.Entity;
				if (((previousValue != value) 
							|| (this._QL_ViTri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_ViTri.Entity = null;
						previousValue.QL_TaiLieus.Remove(this);
					}
					this._QL_ViTri.Entity = value;
					if ((value != null))
					{
						value.QL_TaiLieus.Add(this);
						this._ViTri = value.MaViTri;
					}
					else
					{
						this._ViTri = default(string);
					}
					this.SendPropertyChanged("QL_ViTri");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TacGia_QL_TaiLieu", Storage="_QL_TacGia", ThisKey="MaTacGia", OtherKey="MaTacGia", IsForeignKey=true)]
		public QL_TacGia QL_TacGia
		{
			get
			{
				return this._QL_TacGia.Entity;
			}
			set
			{
				QL_TacGia previousValue = this._QL_TacGia.Entity;
				if (((previousValue != value) 
							|| (this._QL_TacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_TacGia.Entity = null;
						previousValue.QL_TaiLieus.Remove(this);
					}
					this._QL_TacGia.Entity = value;
					if ((value != null))
					{
						value.QL_TaiLieus.Add(this);
						this._MaTacGia = value.MaTacGia;
					}
					else
					{
						this._MaTacGia = default(string);
					}
					this.SendPropertyChanged("QL_TacGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhaXuatBan_QL_TaiLieu", Storage="_QL_NhaXuatBan", ThisKey="MaNXB", OtherKey="MaNXB", IsForeignKey=true)]
		public QL_NhaXuatBan QL_NhaXuatBan
		{
			get
			{
				return this._QL_NhaXuatBan.Entity;
			}
			set
			{
				QL_NhaXuatBan previousValue = this._QL_NhaXuatBan.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhaXuatBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhaXuatBan.Entity = null;
						previousValue.QL_TaiLieus.Remove(this);
					}
					this._QL_NhaXuatBan.Entity = value;
					if ((value != null))
					{
						value.QL_TaiLieus.Add(this);
						this._MaNXB = value.MaNXB;
					}
					else
					{
						this._MaNXB = default(string);
					}
					this.SendPropertyChanged("QL_NhaXuatBan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_MuonTras(QL_MuonTra entity)
		{
			this.SendPropertyChanging();
			entity.QL_TaiLieu = this;
		}
		
		private void detach_QL_MuonTras(QL_MuonTra entity)
		{
			this.SendPropertyChanging();
			entity.QL_TaiLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_TacGia")]
	public partial class QL_TacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTacGia;
		
		private string _TenTacGia;
		
		private EntitySet<QL_TaiLieu> _QL_TaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTacGiaChanging(string value);
    partial void OnMaTacGiaChanged();
    partial void OnTenTacGiaChanging(string value);
    partial void OnTenTacGiaChanged();
    #endregion
		
		public QL_TacGia()
		{
			this._QL_TaiLieus = new EntitySet<QL_TaiLieu>(new Action<QL_TaiLieu>(this.attach_QL_TaiLieus), new Action<QL_TaiLieu>(this.detach_QL_TaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTacGia
		{
			get
			{
				return this._MaTacGia;
			}
			set
			{
				if ((this._MaTacGia != value))
				{
					this.OnMaTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaTacGia = value;
					this.SendPropertyChanged("MaTacGia");
					this.OnMaTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTacGia", DbType="NVarChar(50)")]
		public string TenTacGia
		{
			get
			{
				return this._TenTacGia;
			}
			set
			{
				if ((this._TenTacGia != value))
				{
					this.OnTenTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TenTacGia = value;
					this.SendPropertyChanged("TenTacGia");
					this.OnTenTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TacGia_QL_TaiLieu", Storage="_QL_TaiLieus", ThisKey="MaTacGia", OtherKey="MaTacGia")]
		public EntitySet<QL_TaiLieu> QL_TaiLieus
		{
			get
			{
				return this._QL_TaiLieus;
			}
			set
			{
				this._QL_TaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TacGia = this;
		}
		
		private void detach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NhomCuaNguoiDung")]
	public partial class QL_NhomCuaNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private int _Quyen;
		
		private EntitySet<QL_NguoiDung> _QL_NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnQuyenChanging(int value);
    partial void OnQuyenChanged();
    #endregion
		
		public QL_NhomCuaNguoiDung()
		{
			this._QL_NguoiDungs = new EntitySet<QL_NguoiDung>(new Action<QL_NguoiDung>(this.attach_QL_NguoiDungs), new Action<QL_NguoiDung>(this.detach_QL_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="Int NOT NULL")]
		public int Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomCuaNguoiDung_QL_NguoiDung", Storage="_QL_NguoiDungs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<QL_NguoiDung> QL_NguoiDungs
		{
			get
			{
				return this._QL_NguoiDungs;
			}
			set
			{
				this._QL_NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_NguoiDungs(QL_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomCuaNguoiDung = this;
		}
		
		private void detach_QL_NguoiDungs(QL_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomCuaNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NguoiDung")]
	public partial class QL_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _MaNhom;
		
		private EntitySet<QL_MuonTra> _QL_MuonTras;
		
		private EntityRef<QL_NhomCuaNguoiDung> _QL_NhomCuaNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    #endregion
		
		public QL_NguoiDung()
		{
			this._QL_MuonTras = new EntitySet<QL_MuonTra>(new Action<QL_MuonTra>(this.attach_QL_MuonTras), new Action<QL_MuonTra>(this.detach_QL_MuonTras));
			this._QL_NhomCuaNguoiDung = default(EntityRef<QL_NhomCuaNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._QL_NhomCuaNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_MuonTra", Storage="_QL_MuonTras", ThisKey="TenDangNhap", OtherKey="TenDangNhap")]
		public EntitySet<QL_MuonTra> QL_MuonTras
		{
			get
			{
				return this._QL_MuonTras;
			}
			set
			{
				this._QL_MuonTras.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomCuaNguoiDung_QL_NguoiDung", Storage="_QL_NhomCuaNguoiDung", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public QL_NhomCuaNguoiDung QL_NhomCuaNguoiDung
		{
			get
			{
				return this._QL_NhomCuaNguoiDung.Entity;
			}
			set
			{
				QL_NhomCuaNguoiDung previousValue = this._QL_NhomCuaNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhomCuaNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhomCuaNguoiDung.Entity = null;
						previousValue.QL_NguoiDungs.Remove(this);
					}
					this._QL_NhomCuaNguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_NguoiDungs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("QL_NhomCuaNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_MuonTras(QL_MuonTra entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = this;
		}
		
		private void detach_QL_MuonTras(QL_MuonTra entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NhaXuatBan")]
	public partial class QL_NhaXuatBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNXB;
		
		private string _TenNXB;
		
		private EntitySet<QL_TaiLieu> _QL_TaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    partial void OnTenNXBChanging(string value);
    partial void OnTenNXBChanged();
    #endregion
		
		public QL_NhaXuatBan()
		{
			this._QL_TaiLieus = new EntitySet<QL_TaiLieu>(new Action<QL_TaiLieu>(this.attach_QL_TaiLieus), new Action<QL_TaiLieu>(this.detach_QL_TaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNXB", DbType="NVarChar(50)")]
		public string TenNXB
		{
			get
			{
				return this._TenNXB;
			}
			set
			{
				if ((this._TenNXB != value))
				{
					this.OnTenNXBChanging(value);
					this.SendPropertyChanging();
					this._TenNXB = value;
					this.SendPropertyChanged("TenNXB");
					this.OnTenNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhaXuatBan_QL_TaiLieu", Storage="_QL_TaiLieus", ThisKey="MaNXB", OtherKey="MaNXB")]
		public EntitySet<QL_TaiLieu> QL_TaiLieus
		{
			get
			{
				return this._QL_TaiLieus;
			}
			set
			{
				this._QL_TaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhaXuatBan = this;
		}
		
		private void detach_QL_TaiLieus(QL_TaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhaXuatBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_MuonTra")]
	public partial class QL_MuonTra : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuMuon;
		
		private string _MaTaiLieu;
		
		private string _SoLuongMuon;
		
		private System.Nullable<System.DateTime> _NgayMuon;
		
		private System.Nullable<System.DateTime> _NgayTra;
		
		private string _MaDocGia;
		
		private string _TenDangNhap;
		
		private EntityRef<QL_NguoiDung> _QL_NguoiDung;
		
		private EntityRef<QL_TaiLieu> _QL_TaiLieu;
		
		private EntityRef<QL_DocGia> _QL_DocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuMuonChanging(string value);
    partial void OnMaPhieuMuonChanged();
    partial void OnMaTaiLieuChanging(string value);
    partial void OnMaTaiLieuChanged();
    partial void OnSoLuongMuonChanging(string value);
    partial void OnSoLuongMuonChanged();
    partial void OnNgayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuonChanged();
    partial void OnNgayTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTraChanged();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    #endregion
		
		public QL_MuonTra()
		{
			this._QL_NguoiDung = default(EntityRef<QL_NguoiDung>);
			this._QL_TaiLieu = default(EntityRef<QL_TaiLieu>);
			this._QL_DocGia = default(EntityRef<QL_DocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuMuon", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuMuon
		{
			get
			{
				return this._MaPhieuMuon;
			}
			set
			{
				if ((this._MaPhieuMuon != value))
				{
					this.OnMaPhieuMuonChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuMuon = value;
					this.SendPropertyChanged("MaPhieuMuon");
					this.OnMaPhieuMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiLieu", DbType="NVarChar(50)")]
		public string MaTaiLieu
		{
			get
			{
				return this._MaTaiLieu;
			}
			set
			{
				if ((this._MaTaiLieu != value))
				{
					if (this._QL_TaiLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._MaTaiLieu = value;
					this.SendPropertyChanged("MaTaiLieu");
					this.OnMaTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongMuon", DbType="NVarChar(50)")]
		public string SoLuongMuon
		{
			get
			{
				return this._SoLuongMuon;
			}
			set
			{
				if ((this._SoLuongMuon != value))
				{
					this.OnSoLuongMuonChanging(value);
					this.SendPropertyChanging();
					this._SoLuongMuon = value;
					this.SendPropertyChanged("SoLuongMuon");
					this.OnSoLuongMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTra", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTra
		{
			get
			{
				return this._NgayTra;
			}
			set
			{
				if ((this._NgayTra != value))
				{
					this.OnNgayTraChanging(value);
					this.SendPropertyChanging();
					this._NgayTra = value;
					this.SendPropertyChanged("NgayTra");
					this.OnNgayTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="NVarChar(50)")]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					if (this._QL_DocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50)")]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					if (this._QL_NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_MuonTra", Storage="_QL_NguoiDung", ThisKey="TenDangNhap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public QL_NguoiDung QL_NguoiDung
		{
			get
			{
				return this._QL_NguoiDung.Entity;
			}
			set
			{
				QL_NguoiDung previousValue = this._QL_NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NguoiDung.Entity = null;
						previousValue.QL_MuonTras.Remove(this);
					}
					this._QL_NguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_MuonTras.Add(this);
						this._TenDangNhap = value.TenDangNhap;
					}
					else
					{
						this._TenDangNhap = default(string);
					}
					this.SendPropertyChanged("QL_NguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TaiLieu_QL_MuonTra", Storage="_QL_TaiLieu", ThisKey="MaTaiLieu", OtherKey="MaTaiLieu", IsForeignKey=true)]
		public QL_TaiLieu QL_TaiLieu
		{
			get
			{
				return this._QL_TaiLieu.Entity;
			}
			set
			{
				QL_TaiLieu previousValue = this._QL_TaiLieu.Entity;
				if (((previousValue != value) 
							|| (this._QL_TaiLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_TaiLieu.Entity = null;
						previousValue.QL_MuonTras.Remove(this);
					}
					this._QL_TaiLieu.Entity = value;
					if ((value != null))
					{
						value.QL_MuonTras.Add(this);
						this._MaTaiLieu = value.MaTaiLieu;
					}
					else
					{
						this._MaTaiLieu = default(string);
					}
					this.SendPropertyChanged("QL_TaiLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_DocGia_QL_MuonTra", Storage="_QL_DocGia", ThisKey="MaDocGia", OtherKey="MaDocGia", IsForeignKey=true)]
		public QL_DocGia QL_DocGia
		{
			get
			{
				return this._QL_DocGia.Entity;
			}
			set
			{
				QL_DocGia previousValue = this._QL_DocGia.Entity;
				if (((previousValue != value) 
							|| (this._QL_DocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_DocGia.Entity = null;
						previousValue.QL_MuonTras.Remove(this);
					}
					this._QL_DocGia.Entity = value;
					if ((value != null))
					{
						value.QL_MuonTras.Add(this);
						this._MaDocGia = value.MaDocGia;
					}
					else
					{
						this._MaDocGia = default(string);
					}
					this.SendPropertyChanged("QL_DocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_LoaiDocGia")]
	public partial class QL_LoaiDocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiDocGia;
		
		private string _TenLoaiDocGia;
		
		private string _GhiChu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiDocGiaChanging(string value);
    partial void OnMaLoaiDocGiaChanged();
    partial void OnTenLoaiDocGiaChanging(string value);
    partial void OnTenLoaiDocGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QL_LoaiDocGia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiDocGia
		{
			get
			{
				return this._MaLoaiDocGia;
			}
			set
			{
				if ((this._MaLoaiDocGia != value))
				{
					this.OnMaLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDocGia = value;
					this.SendPropertyChanged("MaLoaiDocGia");
					this.OnMaLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiDocGia", DbType="NVarChar(50)")]
		public string TenLoaiDocGia
		{
			get
			{
				return this._TenLoaiDocGia;
			}
			set
			{
				if ((this._TenLoaiDocGia != value))
				{
					this.OnTenLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiDocGia = value;
					this.SendPropertyChanged("TenLoaiDocGia");
					this.OnTenLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_DocGia")]
	public partial class QL_DocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDocGia;
		
		private string _TenDocGia;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private System.Data.Linq.Binary _Anh;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _Emai;
		
		private string _LoaiDocGia;
		
		private EntitySet<QL_MuonTra> _QL_MuonTras;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnTenDocGiaChanging(string value);
    partial void OnTenDocGiaChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnAnhChanging(System.Data.Linq.Binary value);
    partial void OnAnhChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnEmaiChanging(string value);
    partial void OnEmaiChanged();
    partial void OnLoaiDocGiaChanging(string value);
    partial void OnLoaiDocGiaChanged();
    #endregion
		
		public QL_DocGia()
		{
			this._QL_MuonTras = new EntitySet<QL_MuonTra>(new Action<QL_MuonTra>(this.attach_QL_MuonTras), new Action<QL_MuonTra>(this.detach_QL_MuonTras));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDocGia", DbType="NVarChar(50)")]
		public string TenDocGia
		{
			get
			{
				return this._TenDocGia;
			}
			set
			{
				if ((this._TenDocGia != value))
				{
					this.OnTenDocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenDocGia = value;
					this.SendPropertyChanged("TenDocGia");
					this.OnTenDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emai", DbType="NVarChar(50)")]
		public string Emai
		{
			get
			{
				return this._Emai;
			}
			set
			{
				if ((this._Emai != value))
				{
					this.OnEmaiChanging(value);
					this.SendPropertyChanging();
					this._Emai = value;
					this.SendPropertyChanged("Emai");
					this.OnEmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDocGia", DbType="NVarChar(50)")]
		public string LoaiDocGia
		{
			get
			{
				return this._LoaiDocGia;
			}
			set
			{
				if ((this._LoaiDocGia != value))
				{
					this.OnLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._LoaiDocGia = value;
					this.SendPropertyChanged("LoaiDocGia");
					this.OnLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_DocGia_QL_MuonTra", Storage="_QL_MuonTras", ThisKey="MaDocGia", OtherKey="MaDocGia")]
		public EntitySet<QL_MuonTra> QL_MuonTras
		{
			get
			{
				return this._QL_MuonTras;
			}
			set
			{
				this._QL_MuonTras.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_MuonTras(QL_MuonTra entity)
		{
			this.SendPropertyChanging();
			entity.QL_DocGia = this;
		}
		
		private void detach_QL_MuonTras(QL_MuonTra entity)
		{
			this.SendPropertyChanging();
			entity.QL_DocGia = null;
		}
	}
}
#pragma warning restore 1591
