#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL_DLL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LTWNC")]
	public partial class QLTVDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQL_ChiTietHoaDon(QL_ChiTietHoaDon instance);
    partial void UpdateQL_ChiTietHoaDon(QL_ChiTietHoaDon instance);
    partial void DeleteQL_ChiTietHoaDon(QL_ChiTietHoaDon instance);
    partial void InsertQL_ChiTietManHinh(QL_ChiTietManHinh instance);
    partial void UpdateQL_ChiTietManHinh(QL_ChiTietManHinh instance);
    partial void DeleteQL_ChiTietManHinh(QL_ChiTietManHinh instance);
    partial void InsertQL_ChiTietTaiLieu(QL_ChiTietTaiLieu instance);
    partial void UpdateQL_ChiTietTaiLieu(QL_ChiTietTaiLieu instance);
    partial void DeleteQL_ChiTietTaiLieu(QL_ChiTietTaiLieu instance);
    partial void InsertQL_DocGia(QL_DocGia instance);
    partial void UpdateQL_DocGia(QL_DocGia instance);
    partial void DeleteQL_DocGia(QL_DocGia instance);
    partial void InsertQL_HoaDon(QL_HoaDon instance);
    partial void UpdateQL_HoaDon(QL_HoaDon instance);
    partial void DeleteQL_HoaDon(QL_HoaDon instance);
    partial void InsertQL_LoaiDocGia(QL_LoaiDocGia instance);
    partial void UpdateQL_LoaiDocGia(QL_LoaiDocGia instance);
    partial void DeleteQL_LoaiDocGia(QL_LoaiDocGia instance);
    partial void InsertQL_ManHinh(QL_ManHinh instance);
    partial void UpdateQL_ManHinh(QL_ManHinh instance);
    partial void DeleteQL_ManHinh(QL_ManHinh instance);
    partial void InsertQL_NguoiDung(QL_NguoiDung instance);
    partial void UpdateQL_NguoiDung(QL_NguoiDung instance);
    partial void DeleteQL_NguoiDung(QL_NguoiDung instance);
    partial void InsertQL_NhaCungCap(QL_NhaCungCap instance);
    partial void UpdateQL_NhaCungCap(QL_NhaCungCap instance);
    partial void DeleteQL_NhaCungCap(QL_NhaCungCap instance);
    partial void InsertQL_NhaXuatBan(QL_NhaXuatBan instance);
    partial void UpdateQL_NhaXuatBan(QL_NhaXuatBan instance);
    partial void DeleteQL_NhaXuatBan(QL_NhaXuatBan instance);
    partial void InsertQL_NhomCuaNguoiDung(QL_NhomCuaNguoiDung instance);
    partial void UpdateQL_NhomCuaNguoiDung(QL_NhomCuaNguoiDung instance);
    partial void DeleteQL_NhomCuaNguoiDung(QL_NhomCuaNguoiDung instance);
    partial void InsertQL_TacGia(QL_TacGia instance);
    partial void UpdateQL_TacGia(QL_TacGia instance);
    partial void DeleteQL_TacGia(QL_TacGia instance);
    partial void InsertQL_TaiLieu(QL_TaiLieu instance);
    partial void UpdateQL_TaiLieu(QL_TaiLieu instance);
    partial void DeleteQL_TaiLieu(QL_TaiLieu instance);
    partial void InsertQL_ViTri(QL_ViTri instance);
    partial void UpdateQL_ViTri(QL_ViTri instance);
    partial void DeleteQL_ViTri(QL_ViTri instance);
    #endregion
		
		public QLTVDataContext() : 
				base(global::BLL_DLL.Properties.Settings.Default.LTWNCConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLTVDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<QL_ChiTietHoaDon> QL_ChiTietHoaDons
		{
			get
			{
				return this.GetTable<QL_ChiTietHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<QL_ChiTietManHinh> QL_ChiTietManHinhs
		{
			get
			{
				return this.GetTable<QL_ChiTietManHinh>();
			}
		}
		
		public System.Data.Linq.Table<QL_ChiTietTaiLieu> QL_ChiTietTaiLieus
		{
			get
			{
				return this.GetTable<QL_ChiTietTaiLieu>();
			}
		}
		
		public System.Data.Linq.Table<QL_DocGia> QL_DocGias
		{
			get
			{
				return this.GetTable<QL_DocGia>();
			}
		}
		
		public System.Data.Linq.Table<QL_HoaDon> QL_HoaDons
		{
			get
			{
				return this.GetTable<QL_HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<QL_LoaiDocGia> QL_LoaiDocGias
		{
			get
			{
				return this.GetTable<QL_LoaiDocGia>();
			}
		}
		
		public System.Data.Linq.Table<QL_ManHinh> QL_ManHinhs
		{
			get
			{
				return this.GetTable<QL_ManHinh>();
			}
		}
		
		public System.Data.Linq.Table<QL_NguoiDung> QL_NguoiDungs
		{
			get
			{
				return this.GetTable<QL_NguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_NhaCungCap> QL_NhaCungCaps
		{
			get
			{
				return this.GetTable<QL_NhaCungCap>();
			}
		}
		
		public System.Data.Linq.Table<QL_NhaXuatBan> QL_NhaXuatBans
		{
			get
			{
				return this.GetTable<QL_NhaXuatBan>();
			}
		}
		
		public System.Data.Linq.Table<QL_NhomCuaNguoiDung> QL_NhomCuaNguoiDungs
		{
			get
			{
				return this.GetTable<QL_NhomCuaNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<QL_TacGia> QL_TacGias
		{
			get
			{
				return this.GetTable<QL_TacGia>();
			}
		}
		
		public System.Data.Linq.Table<QL_TaiLieu> QL_TaiLieus
		{
			get
			{
				return this.GetTable<QL_TaiLieu>();
			}
		}
		
		public System.Data.Linq.Table<QL_ViTri> QL_ViTris
		{
			get
			{
				return this.GetTable<QL_ViTri>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ChiTietHoaDon")]
	public partial class QL_ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTHD;
		
		private System.Nullable<int> _MaHD;
		
		private System.Nullable<int> _MaTaiLieu;
		
		private System.Nullable<int> _SoLuong;
		
		private string _TrangThai;
		
		private EntityRef<QL_ChiTietTaiLieu> _QL_ChiTietTaiLieu;
		
		private EntityRef<QL_HoaDon> _QL_HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTHDChanging(int value);
    partial void OnMaCTHDChanged();
    partial void OnMaHDChanging(System.Nullable<int> value);
    partial void OnMaHDChanged();
    partial void OnMaTaiLieuChanging(System.Nullable<int> value);
    partial void OnMaTaiLieuChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public QL_ChiTietHoaDon()
		{
			this._QL_ChiTietTaiLieu = default(EntityRef<QL_ChiTietTaiLieu>);
			this._QL_HoaDon = default(EntityRef<QL_HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaCTHD
		{
			get
			{
				return this._MaCTHD;
			}
			set
			{
				if ((this._MaCTHD != value))
				{
					this.OnMaCTHDChanging(value);
					this.SendPropertyChanging();
					this._MaCTHD = value;
					this.SendPropertyChanged("MaCTHD");
					this.OnMaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int")]
		public System.Nullable<int> MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					if (this._QL_HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiLieu", DbType="Int")]
		public System.Nullable<int> MaTaiLieu
		{
			get
			{
				return this._MaTaiLieu;
			}
			set
			{
				if ((this._MaTaiLieu != value))
				{
					if (this._QL_ChiTietTaiLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._MaTaiLieu = value;
					this.SendPropertyChanged("MaTaiLieu");
					this.OnMaTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ChiTietTaiLieu_QL_ChiTietHoaDon", Storage="_QL_ChiTietTaiLieu", ThisKey="MaTaiLieu", OtherKey="MaCTTL", IsForeignKey=true)]
		public QL_ChiTietTaiLieu QL_ChiTietTaiLieu
		{
			get
			{
				return this._QL_ChiTietTaiLieu.Entity;
			}
			set
			{
				QL_ChiTietTaiLieu previousValue = this._QL_ChiTietTaiLieu.Entity;
				if (((previousValue != value) 
							|| (this._QL_ChiTietTaiLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_ChiTietTaiLieu.Entity = null;
						previousValue.QL_ChiTietHoaDons.Remove(this);
					}
					this._QL_ChiTietTaiLieu.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietHoaDons.Add(this);
						this._MaTaiLieu = value.MaCTTL;
					}
					else
					{
						this._MaTaiLieu = default(Nullable<int>);
					}
					this.SendPropertyChanged("QL_ChiTietTaiLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_HoaDon_QL_ChiTietHoaDon", Storage="_QL_HoaDon", ThisKey="MaHD", OtherKey="MaHD", IsForeignKey=true)]
		public QL_HoaDon QL_HoaDon
		{
			get
			{
				return this._QL_HoaDon.Entity;
			}
			set
			{
				QL_HoaDon previousValue = this._QL_HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._QL_HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_HoaDon.Entity = null;
						previousValue.QL_ChiTietHoaDons.Remove(this);
					}
					this._QL_HoaDon.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietHoaDons.Add(this);
						this._MaHD = value.MaHD;
					}
					else
					{
						this._MaHD = default(Nullable<int>);
					}
					this.SendPropertyChanged("QL_HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ChiTietManHinh")]
	public partial class QL_ChiTietManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _MaNhom;
		
		private string _MaManHinh;
		
		private EntityRef<QL_ManHinh> _QL_ManHinh;
		
		private EntityRef<QL_NhomCuaNguoiDung> _QL_NhomCuaNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    #endregion
		
		public QL_ChiTietManHinh()
		{
			this._QL_ManHinh = default(EntityRef<QL_ManHinh>);
			this._QL_NhomCuaNguoiDung = default(EntityRef<QL_NhomCuaNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20)")]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._QL_NhomCuaNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NVarChar(50)")]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					if (this._QL_ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ManHinh_QL_ChiTietManHinh", Storage="_QL_ManHinh", ThisKey="MaManHinh", OtherKey="MaManHinh", IsForeignKey=true)]
		public QL_ManHinh QL_ManHinh
		{
			get
			{
				return this._QL_ManHinh.Entity;
			}
			set
			{
				QL_ManHinh previousValue = this._QL_ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._QL_ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_ManHinh.Entity = null;
						previousValue.QL_ChiTietManHinhs.Remove(this);
					}
					this._QL_ManHinh.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietManHinhs.Add(this);
						this._MaManHinh = value.MaManHinh;
					}
					else
					{
						this._MaManHinh = default(string);
					}
					this.SendPropertyChanged("QL_ManHinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomCuaNguoiDung_QL_ChiTietManHinh", Storage="_QL_NhomCuaNguoiDung", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public QL_NhomCuaNguoiDung QL_NhomCuaNguoiDung
		{
			get
			{
				return this._QL_NhomCuaNguoiDung.Entity;
			}
			set
			{
				QL_NhomCuaNguoiDung previousValue = this._QL_NhomCuaNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhomCuaNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhomCuaNguoiDung.Entity = null;
						previousValue.QL_ChiTietManHinhs.Remove(this);
					}
					this._QL_NhomCuaNguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietManHinhs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("QL_NhomCuaNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ChiTietTaiLieu")]
	public partial class QL_ChiTietTaiLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCTTL;
		
		private string _MaTaiLieu;
		
		private string _MaNCC;
		
		private string _MaNXB;
		
		private string _MaTG;
		
		private string _MaViTri;
		
		private string _Link;
		
		private string _SoTrang;
		
		private System.Data.Linq.Binary _AnhTaiLieu;
		
		private System.Data.Linq.Binary _AnhQR;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private string _NguoiNhap;
		
		private string _TenChiTiet;
		
		private System.Nullable<int> _SoLuong;
		
		private System.Nullable<decimal> _GiaBia;
		
		private System.Nullable<decimal> _GiaNhap;
		
		private EntitySet<QL_ChiTietHoaDon> _QL_ChiTietHoaDons;
		
		private EntityRef<QL_NhaCungCap> _QL_NhaCungCap;
		
		private EntityRef<QL_NhaXuatBan> _QL_NhaXuatBan;
		
		private EntityRef<QL_TacGia> _QL_TacGia;
		
		private EntityRef<QL_TaiLieu> _QL_TaiLieu;
		
		private EntityRef<QL_ViTri> _QL_ViTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCTTLChanging(int value);
    partial void OnMaCTTLChanged();
    partial void OnMaTaiLieuChanging(string value);
    partial void OnMaTaiLieuChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    partial void OnMaTGChanging(string value);
    partial void OnMaTGChanged();
    partial void OnMaViTriChanging(string value);
    partial void OnMaViTriChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnSoTrangChanging(string value);
    partial void OnSoTrangChanged();
    partial void OnAnhTaiLieuChanging(System.Data.Linq.Binary value);
    partial void OnAnhTaiLieuChanged();
    partial void OnAnhQRChanging(System.Data.Linq.Binary value);
    partial void OnAnhQRChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnNguoiNhapChanging(string value);
    partial void OnNguoiNhapChanged();
    partial void OnTenChiTietChanging(string value);
    partial void OnTenChiTietChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnGiaBiaChanging(System.Nullable<decimal> value);
    partial void OnGiaBiaChanged();
    partial void OnGiaNhapChanging(System.Nullable<decimal> value);
    partial void OnGiaNhapChanged();
    #endregion
		
		public QL_ChiTietTaiLieu()
		{
			this._QL_ChiTietHoaDons = new EntitySet<QL_ChiTietHoaDon>(new Action<QL_ChiTietHoaDon>(this.attach_QL_ChiTietHoaDons), new Action<QL_ChiTietHoaDon>(this.detach_QL_ChiTietHoaDons));
			this._QL_NhaCungCap = default(EntityRef<QL_NhaCungCap>);
			this._QL_NhaXuatBan = default(EntityRef<QL_NhaXuatBan>);
			this._QL_TacGia = default(EntityRef<QL_TacGia>);
			this._QL_TaiLieu = default(EntityRef<QL_TaiLieu>);
			this._QL_ViTri = default(EntityRef<QL_ViTri>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCTTL", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaCTTL
		{
			get
			{
				return this._MaCTTL;
			}
			set
			{
				if ((this._MaCTTL != value))
				{
					this.OnMaCTTLChanging(value);
					this.SendPropertyChanging();
					this._MaCTTL = value;
					this.SendPropertyChanged("MaCTTL");
					this.OnMaCTTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiLieu", DbType="NVarChar(50)")]
		public string MaTaiLieu
		{
			get
			{
				return this._MaTaiLieu;
			}
			set
			{
				if ((this._MaTaiLieu != value))
				{
					if (this._QL_TaiLieu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._MaTaiLieu = value;
					this.SendPropertyChanged("MaTaiLieu");
					this.OnMaTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(50)")]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._QL_NhaCungCap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="NVarChar(50)")]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					if (this._QL_NhaXuatBan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTG", DbType="NVarChar(50)")]
		public string MaTG
		{
			get
			{
				return this._MaTG;
			}
			set
			{
				if ((this._MaTG != value))
				{
					if (this._QL_TacGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTGChanging(value);
					this.SendPropertyChanging();
					this._MaTG = value;
					this.SendPropertyChanged("MaTG");
					this.OnMaTGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(50)")]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					if (this._QL_ViTri.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaViTriChanging(value);
					this.SendPropertyChanging();
					this._MaViTri = value;
					this.SendPropertyChanged("MaViTri");
					this.OnMaViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(MAX)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTrang", DbType="NVarChar(50)")]
		public string SoTrang
		{
			get
			{
				return this._SoTrang;
			}
			set
			{
				if ((this._SoTrang != value))
				{
					this.OnSoTrangChanging(value);
					this.SendPropertyChanging();
					this._SoTrang = value;
					this.SendPropertyChanged("SoTrang");
					this.OnSoTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhTaiLieu", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AnhTaiLieu
		{
			get
			{
				return this._AnhTaiLieu;
			}
			set
			{
				if ((this._AnhTaiLieu != value))
				{
					this.OnAnhTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._AnhTaiLieu = value;
					this.SendPropertyChanged("AnhTaiLieu");
					this.OnAnhTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhQR", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AnhQR
		{
			get
			{
				return this._AnhQR;
			}
			set
			{
				if ((this._AnhQR != value))
				{
					this.OnAnhQRChanging(value);
					this.SendPropertyChanging();
					this._AnhQR = value;
					this.SendPropertyChanged("AnhQR");
					this.OnAnhQRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiNhap", DbType="NVarChar(50)")]
		public string NguoiNhap
		{
			get
			{
				return this._NguoiNhap;
			}
			set
			{
				if ((this._NguoiNhap != value))
				{
					this.OnNguoiNhapChanging(value);
					this.SendPropertyChanging();
					this._NguoiNhap = value;
					this.SendPropertyChanged("NguoiNhap");
					this.OnNguoiNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChiTiet", DbType="NVarChar(50)")]
		public string TenChiTiet
		{
			get
			{
				return this._TenChiTiet;
			}
			set
			{
				if ((this._TenChiTiet != value))
				{
					this.OnTenChiTietChanging(value);
					this.SendPropertyChanging();
					this._TenChiTiet = value;
					this.SendPropertyChanged("TenChiTiet");
					this.OnTenChiTietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaBia", DbType="Money")]
		public System.Nullable<decimal> GiaBia
		{
			get
			{
				return this._GiaBia;
			}
			set
			{
				if ((this._GiaBia != value))
				{
					this.OnGiaBiaChanging(value);
					this.SendPropertyChanging();
					this._GiaBia = value;
					this.SendPropertyChanged("GiaBia");
					this.OnGiaBiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GiaNhap", DbType="Money")]
		public System.Nullable<decimal> GiaNhap
		{
			get
			{
				return this._GiaNhap;
			}
			set
			{
				if ((this._GiaNhap != value))
				{
					this.OnGiaNhapChanging(value);
					this.SendPropertyChanging();
					this._GiaNhap = value;
					this.SendPropertyChanged("GiaNhap");
					this.OnGiaNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ChiTietTaiLieu_QL_ChiTietHoaDon", Storage="_QL_ChiTietHoaDons", ThisKey="MaCTTL", OtherKey="MaTaiLieu")]
		public EntitySet<QL_ChiTietHoaDon> QL_ChiTietHoaDons
		{
			get
			{
				return this._QL_ChiTietHoaDons;
			}
			set
			{
				this._QL_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhaCungCap_QL_ChiTietTaiLieu", Storage="_QL_NhaCungCap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public QL_NhaCungCap QL_NhaCungCap
		{
			get
			{
				return this._QL_NhaCungCap.Entity;
			}
			set
			{
				QL_NhaCungCap previousValue = this._QL_NhaCungCap.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhaCungCap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhaCungCap.Entity = null;
						previousValue.QL_ChiTietTaiLieus.Remove(this);
					}
					this._QL_NhaCungCap.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietTaiLieus.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("QL_NhaCungCap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhaXuatBan_QL_ChiTietTaiLieu", Storage="_QL_NhaXuatBan", ThisKey="MaNXB", OtherKey="MaNXB", IsForeignKey=true)]
		public QL_NhaXuatBan QL_NhaXuatBan
		{
			get
			{
				return this._QL_NhaXuatBan.Entity;
			}
			set
			{
				QL_NhaXuatBan previousValue = this._QL_NhaXuatBan.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhaXuatBan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhaXuatBan.Entity = null;
						previousValue.QL_ChiTietTaiLieus.Remove(this);
					}
					this._QL_NhaXuatBan.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietTaiLieus.Add(this);
						this._MaNXB = value.MaNXB;
					}
					else
					{
						this._MaNXB = default(string);
					}
					this.SendPropertyChanged("QL_NhaXuatBan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TacGia_QL_ChiTietTaiLieu", Storage="_QL_TacGia", ThisKey="MaTG", OtherKey="MaTacGia", IsForeignKey=true)]
		public QL_TacGia QL_TacGia
		{
			get
			{
				return this._QL_TacGia.Entity;
			}
			set
			{
				QL_TacGia previousValue = this._QL_TacGia.Entity;
				if (((previousValue != value) 
							|| (this._QL_TacGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_TacGia.Entity = null;
						previousValue.QL_ChiTietTaiLieus.Remove(this);
					}
					this._QL_TacGia.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietTaiLieus.Add(this);
						this._MaTG = value.MaTacGia;
					}
					else
					{
						this._MaTG = default(string);
					}
					this.SendPropertyChanged("QL_TacGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TaiLieu_QL_ChiTietTaiLieu", Storage="_QL_TaiLieu", ThisKey="MaTaiLieu", OtherKey="MaTaiLieu", IsForeignKey=true)]
		public QL_TaiLieu QL_TaiLieu
		{
			get
			{
				return this._QL_TaiLieu.Entity;
			}
			set
			{
				QL_TaiLieu previousValue = this._QL_TaiLieu.Entity;
				if (((previousValue != value) 
							|| (this._QL_TaiLieu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_TaiLieu.Entity = null;
						previousValue.QL_ChiTietTaiLieus.Remove(this);
					}
					this._QL_TaiLieu.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietTaiLieus.Add(this);
						this._MaTaiLieu = value.MaTaiLieu;
					}
					else
					{
						this._MaTaiLieu = default(string);
					}
					this.SendPropertyChanged("QL_TaiLieu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ViTri_QL_ChiTietTaiLieu", Storage="_QL_ViTri", ThisKey="MaViTri", OtherKey="MaViTri", IsForeignKey=true)]
		public QL_ViTri QL_ViTri
		{
			get
			{
				return this._QL_ViTri.Entity;
			}
			set
			{
				QL_ViTri previousValue = this._QL_ViTri.Entity;
				if (((previousValue != value) 
							|| (this._QL_ViTri.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_ViTri.Entity = null;
						previousValue.QL_ChiTietTaiLieus.Remove(this);
					}
					this._QL_ViTri.Entity = value;
					if ((value != null))
					{
						value.QL_ChiTietTaiLieus.Add(this);
						this._MaViTri = value.MaViTri;
					}
					else
					{
						this._MaViTri = default(string);
					}
					this.SendPropertyChanged("QL_ViTri");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_ChiTietTaiLieu = this;
		}
		
		private void detach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_ChiTietTaiLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_DocGia")]
	public partial class QL_DocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDocGia;
		
		private string _TenDocGia;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _SoDienThoai;
		
		private System.Data.Linq.Binary _Anh;
		
		private System.Nullable<System.DateTime> _NgayTao;
		
		private string _Emai;
		
		private string _LoaiDocGia;
		
		private System.Data.Linq.Binary _AnhDocGia;
		
		private EntitySet<QL_HoaDon> _QL_HoaDons;
		
		private EntityRef<QL_LoaiDocGia> _QL_LoaiDocGia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnTenDocGiaChanging(string value);
    partial void OnTenDocGiaChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnAnhChanging(System.Data.Linq.Binary value);
    partial void OnAnhChanged();
    partial void OnNgayTaoChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayTaoChanged();
    partial void OnEmaiChanging(string value);
    partial void OnEmaiChanged();
    partial void OnLoaiDocGiaChanging(string value);
    partial void OnLoaiDocGiaChanged();
    partial void OnAnhDocGiaChanging(System.Data.Linq.Binary value);
    partial void OnAnhDocGiaChanged();
    #endregion
		
		public QL_DocGia()
		{
			this._QL_HoaDons = new EntitySet<QL_HoaDon>(new Action<QL_HoaDon>(this.attach_QL_HoaDons), new Action<QL_HoaDon>(this.detach_QL_HoaDons));
			this._QL_LoaiDocGia = default(EntityRef<QL_LoaiDocGia>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDocGia", DbType="NVarChar(50)")]
		public string TenDocGia
		{
			get
			{
				return this._TenDocGia;
			}
			set
			{
				if ((this._TenDocGia != value))
				{
					this.OnTenDocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenDocGia = value;
					this.SendPropertyChanged("TenDocGia");
					this.OnTenDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(50)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="NVarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emai", DbType="NVarChar(50)")]
		public string Emai
		{
			get
			{
				return this._Emai;
			}
			set
			{
				if ((this._Emai != value))
				{
					this.OnEmaiChanging(value);
					this.SendPropertyChanging();
					this._Emai = value;
					this.SendPropertyChanged("Emai");
					this.OnEmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiDocGia", DbType="NVarChar(50)")]
		public string LoaiDocGia
		{
			get
			{
				return this._LoaiDocGia;
			}
			set
			{
				if ((this._LoaiDocGia != value))
				{
					if (this._QL_LoaiDocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._LoaiDocGia = value;
					this.SendPropertyChanged("LoaiDocGia");
					this.OnLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhDocGia", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary AnhDocGia
		{
			get
			{
				return this._AnhDocGia;
			}
			set
			{
				if ((this._AnhDocGia != value))
				{
					this.OnAnhDocGiaChanging(value);
					this.SendPropertyChanging();
					this._AnhDocGia = value;
					this.SendPropertyChanged("AnhDocGia");
					this.OnAnhDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_DocGia_QL_HoaDon", Storage="_QL_HoaDons", ThisKey="MaDocGia", OtherKey="MaDocGia")]
		public EntitySet<QL_HoaDon> QL_HoaDons
		{
			get
			{
				return this._QL_HoaDons;
			}
			set
			{
				this._QL_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_LoaiDocGia_QL_DocGia", Storage="_QL_LoaiDocGia", ThisKey="LoaiDocGia", OtherKey="MaLoaiDocGia", IsForeignKey=true)]
		public QL_LoaiDocGia QL_LoaiDocGia
		{
			get
			{
				return this._QL_LoaiDocGia.Entity;
			}
			set
			{
				QL_LoaiDocGia previousValue = this._QL_LoaiDocGia.Entity;
				if (((previousValue != value) 
							|| (this._QL_LoaiDocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_LoaiDocGia.Entity = null;
						previousValue.QL_DocGias.Remove(this);
					}
					this._QL_LoaiDocGia.Entity = value;
					if ((value != null))
					{
						value.QL_DocGias.Add(this);
						this._LoaiDocGia = value.MaLoaiDocGia;
					}
					else
					{
						this._LoaiDocGia = default(string);
					}
					this.SendPropertyChanged("QL_LoaiDocGia");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_HoaDons(QL_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_DocGia = this;
		}
		
		private void detach_QL_HoaDons(QL_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_DocGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_HoaDon")]
	public partial class QL_HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaHD;
		
		private string _NguoiLap;
		
		private string _MaDocGia;
		
		private System.Nullable<System.DateTime> _NgayMuon;
		
		private System.Nullable<System.DateTime> _NgayHenTra;
		
		private System.Nullable<int> _TongSoLuong;
		
		private string _TrangThai;
		
		private string _GhiChu;
		
		private EntitySet<QL_ChiTietHoaDon> _QL_ChiTietHoaDons;
		
		private EntityRef<QL_DocGia> _QL_DocGia;
		
		private EntityRef<QL_NguoiDung> _QL_NguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHDChanging(int value);
    partial void OnMaHDChanged();
    partial void OnNguoiLapChanging(string value);
    partial void OnNguoiLapChanged();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnNgayMuonChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayMuonChanged();
    partial void OnNgayHenTraChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHenTraChanged();
    partial void OnTongSoLuongChanging(System.Nullable<int> value);
    partial void OnTongSoLuongChanged();
    partial void OnTrangThaiChanging(string value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QL_HoaDon()
		{
			this._QL_ChiTietHoaDons = new EntitySet<QL_ChiTietHoaDon>(new Action<QL_ChiTietHoaDon>(this.attach_QL_ChiTietHoaDons), new Action<QL_ChiTietHoaDon>(this.detach_QL_ChiTietHoaDons));
			this._QL_DocGia = default(EntityRef<QL_DocGia>);
			this._QL_NguoiDung = default(EntityRef<QL_NguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHD", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaHD
		{
			get
			{
				return this._MaHD;
			}
			set
			{
				if ((this._MaHD != value))
				{
					this.OnMaHDChanging(value);
					this.SendPropertyChanging();
					this._MaHD = value;
					this.SendPropertyChanged("MaHD");
					this.OnMaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiLap", DbType="NVarChar(50)")]
		public string NguoiLap
		{
			get
			{
				return this._NguoiLap;
			}
			set
			{
				if ((this._NguoiLap != value))
				{
					if (this._QL_NguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoiLapChanging(value);
					this.SendPropertyChanging();
					this._NguoiLap = value;
					this.SendPropertyChanged("NguoiLap");
					this.OnNguoiLapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="NVarChar(50)")]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					if (this._QL_DocGia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayMuon", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayMuon
		{
			get
			{
				return this._NgayMuon;
			}
			set
			{
				if ((this._NgayMuon != value))
				{
					this.OnNgayMuonChanging(value);
					this.SendPropertyChanging();
					this._NgayMuon = value;
					this.SendPropertyChanged("NgayMuon");
					this.OnNgayMuonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHenTra", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHenTra
		{
			get
			{
				return this._NgayHenTra;
			}
			set
			{
				if ((this._NgayHenTra != value))
				{
					this.OnNgayHenTraChanging(value);
					this.SendPropertyChanging();
					this._NgayHenTra = value;
					this.SendPropertyChanged("NgayHenTra");
					this.OnNgayHenTraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoLuong", DbType="Int")]
		public System.Nullable<int> TongSoLuong
		{
			get
			{
				return this._TongSoLuong;
			}
			set
			{
				if ((this._TongSoLuong != value))
				{
					this.OnTongSoLuongChanging(value);
					this.SendPropertyChanging();
					this._TongSoLuong = value;
					this.SendPropertyChanged("TongSoLuong");
					this.OnTongSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="NVarChar(50)")]
		public string TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_HoaDon_QL_ChiTietHoaDon", Storage="_QL_ChiTietHoaDons", ThisKey="MaHD", OtherKey="MaHD")]
		public EntitySet<QL_ChiTietHoaDon> QL_ChiTietHoaDons
		{
			get
			{
				return this._QL_ChiTietHoaDons;
			}
			set
			{
				this._QL_ChiTietHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_DocGia_QL_HoaDon", Storage="_QL_DocGia", ThisKey="MaDocGia", OtherKey="MaDocGia", IsForeignKey=true)]
		public QL_DocGia QL_DocGia
		{
			get
			{
				return this._QL_DocGia.Entity;
			}
			set
			{
				QL_DocGia previousValue = this._QL_DocGia.Entity;
				if (((previousValue != value) 
							|| (this._QL_DocGia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_DocGia.Entity = null;
						previousValue.QL_HoaDons.Remove(this);
					}
					this._QL_DocGia.Entity = value;
					if ((value != null))
					{
						value.QL_HoaDons.Add(this);
						this._MaDocGia = value.MaDocGia;
					}
					else
					{
						this._MaDocGia = default(string);
					}
					this.SendPropertyChanged("QL_DocGia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_HoaDon", Storage="_QL_NguoiDung", ThisKey="NguoiLap", OtherKey="TenDangNhap", IsForeignKey=true)]
		public QL_NguoiDung QL_NguoiDung
		{
			get
			{
				return this._QL_NguoiDung.Entity;
			}
			set
			{
				QL_NguoiDung previousValue = this._QL_NguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NguoiDung.Entity = null;
						previousValue.QL_HoaDons.Remove(this);
					}
					this._QL_NguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_HoaDons.Add(this);
						this._NguoiLap = value.TenDangNhap;
					}
					else
					{
						this._NguoiLap = default(string);
					}
					this.SendPropertyChanged("QL_NguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_HoaDon = this;
		}
		
		private void detach_QL_ChiTietHoaDons(QL_ChiTietHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_LoaiDocGia")]
	public partial class QL_LoaiDocGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiDocGia;
		
		private string _TenLoaiDocGia;
		
		private string _GhiChu;
		
		private EntitySet<QL_DocGia> _QL_DocGias;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiDocGiaChanging(string value);
    partial void OnMaLoaiDocGiaChanged();
    partial void OnTenLoaiDocGiaChanging(string value);
    partial void OnTenLoaiDocGiaChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public QL_LoaiDocGia()
		{
			this._QL_DocGias = new EntitySet<QL_DocGia>(new Action<QL_DocGia>(this.attach_QL_DocGias), new Action<QL_DocGia>(this.detach_QL_DocGias));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiDocGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiDocGia
		{
			get
			{
				return this._MaLoaiDocGia;
			}
			set
			{
				if ((this._MaLoaiDocGia != value))
				{
					this.OnMaLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiDocGia = value;
					this.SendPropertyChanged("MaLoaiDocGia");
					this.OnMaLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiDocGia", DbType="NVarChar(50)")]
		public string TenLoaiDocGia
		{
			get
			{
				return this._TenLoaiDocGia;
			}
			set
			{
				if ((this._TenLoaiDocGia != value))
				{
					this.OnTenLoaiDocGiaChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiDocGia = value;
					this.SendPropertyChanged("TenLoaiDocGia");
					this.OnTenLoaiDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(50)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_LoaiDocGia_QL_DocGia", Storage="_QL_DocGias", ThisKey="MaLoaiDocGia", OtherKey="LoaiDocGia")]
		public EntitySet<QL_DocGia> QL_DocGias
		{
			get
			{
				return this._QL_DocGias;
			}
			set
			{
				this._QL_DocGias.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_DocGias(QL_DocGia entity)
		{
			this.SendPropertyChanging();
			entity.QL_LoaiDocGia = this;
		}
		
		private void detach_QL_DocGias(QL_DocGia entity)
		{
			this.SendPropertyChanging();
			entity.QL_LoaiDocGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ManHinh")]
	public partial class QL_ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaManHinh;
		
		private string _TenManHinh;
		
		private EntitySet<QL_ChiTietManHinh> _QL_ChiTietManHinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaManHinhChanging(string value);
    partial void OnMaManHinhChanged();
    partial void OnTenManHinhChanging(string value);
    partial void OnTenManHinhChanged();
    #endregion
		
		public QL_ManHinh()
		{
			this._QL_ChiTietManHinhs = new EntitySet<QL_ChiTietManHinh>(new Action<QL_ChiTietManHinh>(this.attach_QL_ChiTietManHinhs), new Action<QL_ChiTietManHinh>(this.detach_QL_ChiTietManHinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaManHinh", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaManHinh
		{
			get
			{
				return this._MaManHinh;
			}
			set
			{
				if ((this._MaManHinh != value))
				{
					this.OnMaManHinhChanging(value);
					this.SendPropertyChanging();
					this._MaManHinh = value;
					this.SendPropertyChanged("MaManHinh");
					this.OnMaManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenManHinh", DbType="NVarChar(50)")]
		public string TenManHinh
		{
			get
			{
				return this._TenManHinh;
			}
			set
			{
				if ((this._TenManHinh != value))
				{
					this.OnTenManHinhChanging(value);
					this.SendPropertyChanging();
					this._TenManHinh = value;
					this.SendPropertyChanged("TenManHinh");
					this.OnTenManHinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ManHinh_QL_ChiTietManHinh", Storage="_QL_ChiTietManHinhs", ThisKey="MaManHinh", OtherKey="MaManHinh")]
		public EntitySet<QL_ChiTietManHinh> QL_ChiTietManHinhs
		{
			get
			{
				return this._QL_ChiTietManHinhs;
			}
			set
			{
				this._QL_ChiTietManHinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietManHinhs(QL_ChiTietManHinh entity)
		{
			this.SendPropertyChanging();
			entity.QL_ManHinh = this;
		}
		
		private void detach_QL_ChiTietManHinhs(QL_ChiTietManHinh entity)
		{
			this.SendPropertyChanging();
			entity.QL_ManHinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NguoiDung")]
	public partial class QL_NguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenDangNhap;
		
		private string _MatKhau;
		
		private string _MaNhom;
		
		private EntitySet<QL_HoaDon> _QL_HoaDons;
		
		private EntityRef<QL_NhomCuaNguoiDung> _QL_NhomCuaNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenDangNhapChanging(string value);
    partial void OnTenDangNhapChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    #endregion
		
		public QL_NguoiDung()
		{
			this._QL_HoaDons = new EntitySet<QL_HoaDon>(new Action<QL_HoaDon>(this.attach_QL_HoaDons), new Action<QL_HoaDon>(this.detach_QL_HoaDons));
			this._QL_NhomCuaNguoiDung = default(EntityRef<QL_NhomCuaNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDangNhap", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TenDangNhap
		{
			get
			{
				return this._TenDangNhap;
			}
			set
			{
				if ((this._TenDangNhap != value))
				{
					this.OnTenDangNhapChanging(value);
					this.SendPropertyChanging();
					this._TenDangNhap = value;
					this.SendPropertyChanged("TenDangNhap");
					this.OnTenDangNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					if (this._QL_NhomCuaNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NguoiDung_QL_HoaDon", Storage="_QL_HoaDons", ThisKey="TenDangNhap", OtherKey="NguoiLap")]
		public EntitySet<QL_HoaDon> QL_HoaDons
		{
			get
			{
				return this._QL_HoaDons;
			}
			set
			{
				this._QL_HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomCuaNguoiDung_QL_NguoiDung", Storage="_QL_NhomCuaNguoiDung", ThisKey="MaNhom", OtherKey="MaNhom", IsForeignKey=true)]
		public QL_NhomCuaNguoiDung QL_NhomCuaNguoiDung
		{
			get
			{
				return this._QL_NhomCuaNguoiDung.Entity;
			}
			set
			{
				QL_NhomCuaNguoiDung previousValue = this._QL_NhomCuaNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._QL_NhomCuaNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QL_NhomCuaNguoiDung.Entity = null;
						previousValue.QL_NguoiDungs.Remove(this);
					}
					this._QL_NhomCuaNguoiDung.Entity = value;
					if ((value != null))
					{
						value.QL_NguoiDungs.Add(this);
						this._MaNhom = value.MaNhom;
					}
					else
					{
						this._MaNhom = default(string);
					}
					this.SendPropertyChanged("QL_NhomCuaNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_HoaDons(QL_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = this;
		}
		
		private void detach_QL_HoaDons(QL_HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.QL_NguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NhaCungCap")]
	public partial class QL_NhaCungCap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private EntitySet<QL_ChiTietTaiLieu> _QL_ChiTietTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    #endregion
		
		public QL_NhaCungCap()
		{
			this._QL_ChiTietTaiLieus = new EntitySet<QL_ChiTietTaiLieu>(new Action<QL_ChiTietTaiLieu>(this.attach_QL_ChiTietTaiLieus), new Action<QL_ChiTietTaiLieu>(this.detach_QL_ChiTietTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(50)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhaCungCap_QL_ChiTietTaiLieu", Storage="_QL_ChiTietTaiLieus", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<QL_ChiTietTaiLieu> QL_ChiTietTaiLieus
		{
			get
			{
				return this._QL_ChiTietTaiLieus;
			}
			set
			{
				this._QL_ChiTietTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhaCungCap = this;
		}
		
		private void detach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhaCungCap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NhaXuatBan")]
	public partial class QL_NhaXuatBan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNXB;
		
		private string _TenNXB;
		
		private EntitySet<QL_ChiTietTaiLieu> _QL_ChiTietTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNXBChanging(string value);
    partial void OnMaNXBChanged();
    partial void OnTenNXBChanging(string value);
    partial void OnTenNXBChanged();
    #endregion
		
		public QL_NhaXuatBan()
		{
			this._QL_ChiTietTaiLieus = new EntitySet<QL_ChiTietTaiLieu>(new Action<QL_ChiTietTaiLieu>(this.attach_QL_ChiTietTaiLieus), new Action<QL_ChiTietTaiLieu>(this.detach_QL_ChiTietTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNXB", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNXB
		{
			get
			{
				return this._MaNXB;
			}
			set
			{
				if ((this._MaNXB != value))
				{
					this.OnMaNXBChanging(value);
					this.SendPropertyChanging();
					this._MaNXB = value;
					this.SendPropertyChanged("MaNXB");
					this.OnMaNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNXB", DbType="NVarChar(50)")]
		public string TenNXB
		{
			get
			{
				return this._TenNXB;
			}
			set
			{
				if ((this._TenNXB != value))
				{
					this.OnTenNXBChanging(value);
					this.SendPropertyChanging();
					this._TenNXB = value;
					this.SendPropertyChanged("TenNXB");
					this.OnTenNXBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhaXuatBan_QL_ChiTietTaiLieu", Storage="_QL_ChiTietTaiLieus", ThisKey="MaNXB", OtherKey="MaNXB")]
		public EntitySet<QL_ChiTietTaiLieu> QL_ChiTietTaiLieus
		{
			get
			{
				return this._QL_ChiTietTaiLieus;
			}
			set
			{
				this._QL_ChiTietTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhaXuatBan = this;
		}
		
		private void detach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhaXuatBan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_NhomCuaNguoiDung")]
	public partial class QL_NhomCuaNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhom;
		
		private string _TenNhom;
		
		private int _Quyen;
		
		private EntitySet<QL_ChiTietManHinh> _QL_ChiTietManHinhs;
		
		private EntitySet<QL_NguoiDung> _QL_NguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomChanging(string value);
    partial void OnMaNhomChanged();
    partial void OnTenNhomChanging(string value);
    partial void OnTenNhomChanged();
    partial void OnQuyenChanging(int value);
    partial void OnQuyenChanged();
    #endregion
		
		public QL_NhomCuaNguoiDung()
		{
			this._QL_ChiTietManHinhs = new EntitySet<QL_ChiTietManHinh>(new Action<QL_ChiTietManHinh>(this.attach_QL_ChiTietManHinhs), new Action<QL_ChiTietManHinh>(this.detach_QL_ChiTietManHinhs));
			this._QL_NguoiDungs = new EntitySet<QL_NguoiDung>(new Action<QL_NguoiDung>(this.attach_QL_NguoiDungs), new Action<QL_NguoiDung>(this.detach_QL_NguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhom", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhom
		{
			get
			{
				return this._MaNhom;
			}
			set
			{
				if ((this._MaNhom != value))
				{
					this.OnMaNhomChanging(value);
					this.SendPropertyChanging();
					this._MaNhom = value;
					this.SendPropertyChanged("MaNhom");
					this.OnMaNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhom
		{
			get
			{
				return this._TenNhom;
			}
			set
			{
				if ((this._TenNhom != value))
				{
					this.OnTenNhomChanging(value);
					this.SendPropertyChanging();
					this._TenNhom = value;
					this.SendPropertyChanged("TenNhom");
					this.OnTenNhomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quyen", DbType="Int NOT NULL")]
		public int Quyen
		{
			get
			{
				return this._Quyen;
			}
			set
			{
				if ((this._Quyen != value))
				{
					this.OnQuyenChanging(value);
					this.SendPropertyChanging();
					this._Quyen = value;
					this.SendPropertyChanged("Quyen");
					this.OnQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomCuaNguoiDung_QL_ChiTietManHinh", Storage="_QL_ChiTietManHinhs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<QL_ChiTietManHinh> QL_ChiTietManHinhs
		{
			get
			{
				return this._QL_ChiTietManHinhs;
			}
			set
			{
				this._QL_ChiTietManHinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_NhomCuaNguoiDung_QL_NguoiDung", Storage="_QL_NguoiDungs", ThisKey="MaNhom", OtherKey="MaNhom")]
		public EntitySet<QL_NguoiDung> QL_NguoiDungs
		{
			get
			{
				return this._QL_NguoiDungs;
			}
			set
			{
				this._QL_NguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietManHinhs(QL_ChiTietManHinh entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomCuaNguoiDung = this;
		}
		
		private void detach_QL_ChiTietManHinhs(QL_ChiTietManHinh entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomCuaNguoiDung = null;
		}
		
		private void attach_QL_NguoiDungs(QL_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomCuaNguoiDung = this;
		}
		
		private void detach_QL_NguoiDungs(QL_NguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.QL_NhomCuaNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_TacGia")]
	public partial class QL_TacGia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTacGia;
		
		private string _TenTacGia;
		
		private EntitySet<QL_ChiTietTaiLieu> _QL_ChiTietTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTacGiaChanging(string value);
    partial void OnMaTacGiaChanged();
    partial void OnTenTacGiaChanging(string value);
    partial void OnTenTacGiaChanged();
    #endregion
		
		public QL_TacGia()
		{
			this._QL_ChiTietTaiLieus = new EntitySet<QL_ChiTietTaiLieu>(new Action<QL_ChiTietTaiLieu>(this.attach_QL_ChiTietTaiLieus), new Action<QL_ChiTietTaiLieu>(this.detach_QL_ChiTietTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTacGia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTacGia
		{
			get
			{
				return this._MaTacGia;
			}
			set
			{
				if ((this._MaTacGia != value))
				{
					this.OnMaTacGiaChanging(value);
					this.SendPropertyChanging();
					this._MaTacGia = value;
					this.SendPropertyChanged("MaTacGia");
					this.OnMaTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTacGia", DbType="NVarChar(50)")]
		public string TenTacGia
		{
			get
			{
				return this._TenTacGia;
			}
			set
			{
				if ((this._TenTacGia != value))
				{
					this.OnTenTacGiaChanging(value);
					this.SendPropertyChanging();
					this._TenTacGia = value;
					this.SendPropertyChanged("TenTacGia");
					this.OnTenTacGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TacGia_QL_ChiTietTaiLieu", Storage="_QL_ChiTietTaiLieus", ThisKey="MaTacGia", OtherKey="MaTG")]
		public EntitySet<QL_ChiTietTaiLieu> QL_ChiTietTaiLieus
		{
			get
			{
				return this._QL_ChiTietTaiLieus;
			}
			set
			{
				this._QL_ChiTietTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TacGia = this;
		}
		
		private void detach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TacGia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_TaiLieu")]
	public partial class QL_TaiLieu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTaiLieu;
		
		private string _TongSoLuong;
		
		private string _NguoiNhap;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private string _TongGiaTien;
		
		private string _TenTaiLieu;
		
		private EntitySet<QL_ChiTietTaiLieu> _QL_ChiTietTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTaiLieuChanging(string value);
    partial void OnMaTaiLieuChanged();
    partial void OnTongSoLuongChanging(string value);
    partial void OnTongSoLuongChanged();
    partial void OnNguoiNhapChanging(string value);
    partial void OnNguoiNhapChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnTongGiaTienChanging(string value);
    partial void OnTongGiaTienChanged();
    partial void OnTenTaiLieuChanging(string value);
    partial void OnTenTaiLieuChanged();
    #endregion
		
		public QL_TaiLieu()
		{
			this._QL_ChiTietTaiLieus = new EntitySet<QL_ChiTietTaiLieu>(new Action<QL_ChiTietTaiLieu>(this.attach_QL_ChiTietTaiLieus), new Action<QL_ChiTietTaiLieu>(this.detach_QL_ChiTietTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTaiLieu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTaiLieu
		{
			get
			{
				return this._MaTaiLieu;
			}
			set
			{
				if ((this._MaTaiLieu != value))
				{
					this.OnMaTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._MaTaiLieu = value;
					this.SendPropertyChanged("MaTaiLieu");
					this.OnMaTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoLuong", DbType="NVarChar(50)")]
		public string TongSoLuong
		{
			get
			{
				return this._TongSoLuong;
			}
			set
			{
				if ((this._TongSoLuong != value))
				{
					this.OnTongSoLuongChanging(value);
					this.SendPropertyChanging();
					this._TongSoLuong = value;
					this.SendPropertyChanged("TongSoLuong");
					this.OnTongSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiNhap", DbType="NVarChar(50)")]
		public string NguoiNhap
		{
			get
			{
				return this._NguoiNhap;
			}
			set
			{
				if ((this._NguoiNhap != value))
				{
					this.OnNguoiNhapChanging(value);
					this.SendPropertyChanging();
					this._NguoiNhap = value;
					this.SendPropertyChanged("NguoiNhap");
					this.OnNguoiNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongGiaTien", DbType="NVarChar(50)")]
		public string TongGiaTien
		{
			get
			{
				return this._TongGiaTien;
			}
			set
			{
				if ((this._TongGiaTien != value))
				{
					this.OnTongGiaTienChanging(value);
					this.SendPropertyChanging();
					this._TongGiaTien = value;
					this.SendPropertyChanged("TongGiaTien");
					this.OnTongGiaTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTaiLieu", DbType="NVarChar(50)")]
		public string TenTaiLieu
		{
			get
			{
				return this._TenTaiLieu;
			}
			set
			{
				if ((this._TenTaiLieu != value))
				{
					this.OnTenTaiLieuChanging(value);
					this.SendPropertyChanging();
					this._TenTaiLieu = value;
					this.SendPropertyChanged("TenTaiLieu");
					this.OnTenTaiLieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_TaiLieu_QL_ChiTietTaiLieu", Storage="_QL_ChiTietTaiLieus", ThisKey="MaTaiLieu", OtherKey="MaTaiLieu")]
		public EntitySet<QL_ChiTietTaiLieu> QL_ChiTietTaiLieus
		{
			get
			{
				return this._QL_ChiTietTaiLieus;
			}
			set
			{
				this._QL_ChiTietTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TaiLieu = this;
		}
		
		private void detach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_TaiLieu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QL_ViTri")]
	public partial class QL_ViTri : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaViTri;
		
		private string _TenViTri;
		
		private EntitySet<QL_ChiTietTaiLieu> _QL_ChiTietTaiLieus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaViTriChanging(string value);
    partial void OnMaViTriChanged();
    partial void OnTenViTriChanging(string value);
    partial void OnTenViTriChanged();
    #endregion
		
		public QL_ViTri()
		{
			this._QL_ChiTietTaiLieus = new EntitySet<QL_ChiTietTaiLieu>(new Action<QL_ChiTietTaiLieu>(this.attach_QL_ChiTietTaiLieus), new Action<QL_ChiTietTaiLieu>(this.detach_QL_ChiTietTaiLieus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTri", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaViTri
		{
			get
			{
				return this._MaViTri;
			}
			set
			{
				if ((this._MaViTri != value))
				{
					this.OnMaViTriChanging(value);
					this.SendPropertyChanging();
					this._MaViTri = value;
					this.SendPropertyChanged("MaViTri");
					this.OnMaViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenViTri", DbType="NVarChar(50)")]
		public string TenViTri
		{
			get
			{
				return this._TenViTri;
			}
			set
			{
				if ((this._TenViTri != value))
				{
					this.OnTenViTriChanging(value);
					this.SendPropertyChanging();
					this._TenViTri = value;
					this.SendPropertyChanged("TenViTri");
					this.OnTenViTriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QL_ViTri_QL_ChiTietTaiLieu", Storage="_QL_ChiTietTaiLieus", ThisKey="MaViTri", OtherKey="MaViTri")]
		public EntitySet<QL_ChiTietTaiLieu> QL_ChiTietTaiLieus
		{
			get
			{
				return this._QL_ChiTietTaiLieus;
			}
			set
			{
				this._QL_ChiTietTaiLieus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_ViTri = this;
		}
		
		private void detach_QL_ChiTietTaiLieus(QL_ChiTietTaiLieu entity)
		{
			this.SendPropertyChanging();
			entity.QL_ViTri = null;
		}
	}
}
#pragma warning restore 1591
